config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  resources :ques do
    collection do

    end

    member do
      patch :help_student
      patch :resolve_student
    end
  end

end

app/models/que.rb
class Que < ActiveRecord::Base
  validates :name, presence: true

  def display_name
    "Mr. #{name}"
  end

  include Workflow
  workflow do
    state :new do
      event :nick_visit, transitions_to: :in_progress
    end
    state :in_progress do
      event :nick_leave, transitions_to: :completed
    end
    state :completed
  end  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  # respond_to :html

  def index
    @people_in_que = Que.where.not(workflow_state: "completed")
    @people_who_are_inifintely_smarter_then_they_were_before_but_still_cant_spell = Que.where(workflow_state: "completed")
    # respond_with @people_in_que
  end
end

app/controllers/ques_controller.rb
class QuesController < ApplicationController
  # def index
  #   # GET
  #   # List of data
  #   # Replaced by our home index CURRENTLY
  # end

  def show
    # GET
    # Shows an individual object
    @que = Que.find params[:id]
  end

  def new
    # GET
    # Brings you to the new page
    @que = Que.new
  end

  def create
    # POST
    # Creates the data
    @que = Que.new que_params
    success = @que.save
    if success == true
      flash[:notice] = "You have successfully entered le Que."
      redirect_to root_path
    else
      flash[:error] = "You need to enter more information before entering le Que."
      render :new
    end
  end

  def edit
    # GET
    # Brings you to the edit page
    @que = Que.find params[:id]
  end

  def update
    # PUT/PATCH
    # Updates existing data
    @que = Que.find params[:id]
    success = @que.update_attributes que_params
    if success == true
      flash[:notice] = "You have successfully updated le Que."
      redirect_to root_path
    else
      flash[:error] = "You need to enter more information before editing your Que."
      render :edit
    end
  end

  def destroy
    # DELETE
    # Deletes stuff
    @que = Que.find params[:id]
    @que.delete
    redirect_to root_path
  end

  def help_student
    @que = Que.find params[:id]
    @que.nick_visit!
    redirect_to root_path
  end

  def resolve_student
    @que = Que.find params[:id]
    @que.nick_leave!
    redirect_to root_path   
  end
  
  private
    def que_params
      params.require(:que).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/ques_helper.rb
module QuesHelper
end

app/views/home/index.html.haml
%div.red_background
  Dude man sup.

.blue_background
  Dude man also sup.

%h4 These Guys are in Queue
= link_to "I need help!", new_que_path
%ul
  - @people_in_que.each do |person|
    %li{ class: "#{person.workflow_state}"}
      = person.name
      (#{person.workflow_state})
      = person.created_at.strftime("%l:%M%p")
      = link_to "Show", que_path(person)
      |
      = link_to "Edit", edit_que_path(person)
      |
      = link_to "Delete", que_path(person), method: :delete
      |
      - if person.workflow_state == 'new'
        = link_to "Help This Student", help_student_que_path(person), method: :patch
      - elsif person.workflow_state == 'in_progress'
        = link_to "Resolve",
          resolve_student_que_path(person), method: :patch

%h4 People Resolved

- @people_who_are_inifintely_smarter_then_they_were_before_but_still_cant_spell.each do |person|
  = person.name
  helped at
  = person.updated_at.strftime("%l:%M%p")
  %br

app/views/layouts/_error_messages.html.haml
- object.errors.messages.each do |k, v|
  - v.each do |message|
    = k.capitalize
    = message
    %br

/ In HAML
/ = is display
/ - is ruby logic that you don't want displayed
/ % is for HTMl tags
/ %div.blue_background
/ .blue_background

app/views/layouts/_flash.html.haml
- if flash[:notice]
  .notice= flash[:notice]
- elsif flash[:error]
  .error= flash[:error]

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Class 12</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <h1>Cool Rails Project</h1>
    <%= render 'layouts/flash' %>
    <%= yield %>

  </body>
</html>

app/views/ques/_form.html.erb
<%= form_for @que do |f| %>
  <%= render 'layouts/error_messages', object: @que %>
  <%= f.label :name %>
  <%= f.text_field :name, placeholder: "Name" %>
  <br>
  <%= f.submit %>
<% end %>
<%= link_to "Home", root_path %>

app/views/ques/edit.html.haml
%h4 Edit Some Person
= render 'form'

app/views/ques/new.html.erb
<h4>New Que</h4>
<%= render 'form' %>

app/views/ques/show.html.haml
%h4 This is a person in que

= @que.name
got into que
= @que.created_at.strftime("%l:%M%p")
%br
= link_to "Home", root_path